{% set version = "4.5.0" %}

package:
  name: apptools
  version: {{ version }}

source:
  fn: apptools-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/a/apptools/apptools-{{ version }}.tar.gz
  sha256: 260ae0e2a86cb2df2fede631ab6ac8ece694a58a1def78cd015c890c57140582

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - traits
    - pyface
    - traitsui
    - configobj
  run:
    - python
    - traits
    - pyface
    - traitsui
    - configobj

test:
  imports:
    - apptools
    - apptools.logger.api

about:
  home: http://docs.enthought.com/apptools/
  license: BSD-3-Clause
  summary: application tools
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - grlee77
