{% set version = "5.3.0" %}

package:
  name: apptools
  version: {{ version }}

source:
  fn: apptools-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/a/apptools/apptools-{{ version }}.tar.gz
  sha256: 30580bf62a0d5dd616edd5e2b9958227633f35cb557c6860452a56809e6bd567

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - traits
    - pyface
    - traitsui
    - configobj
  run:
    - python
    - traits
    - pyface
    - traitsui
    - configobj

test:
  imports:
    - apptools
    - apptools.logger.api

about:
  home: http://docs.enthought.com/apptools/
  license: BSD-3-Clause
  summary: application tools
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - grlee77
