{% set version = "4.4.0" %}

package:
  name: apptools
  version: {{ version }}

source:
  fn: apptools-{{ version }}.tar.bz2
  url: https://pypi.python.org/packages/source/a/apptools/apptools-{{ version }}.tar.bz2
  md5: cf122251faec4d3dff0a9480d6f6f9f7

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - traits
    - pyface
    - traitsui
    - configobj
  run:
    - python
    - traits
    - pyface
    - traitsui
    - configobj

test:
  imports:
    - apptools

about:
  home: http://docs.enthought.com/apptools/
  license: BSD 3-clause
  summary: application tools

extra:
  recipe-maintainers:
    - grlee77
