{% set version = "5.2.0" %}

package:
  name: apptools
  version: {{ version }}

source:
  fn: apptools-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/a/apptools/apptools-{{ version }}.tar.gz
  sha256: 6be8fd98dd836650fffeb1f705c44e28b871651f0bdd0679a2730dd9c3be24fb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - traits
    - pyface
    - traitsui
    - configobj
  run:
    - python
    - traits
    - pyface
    - traitsui
    - configobj

test:
  imports:
    - apptools
    - apptools.logger.api

about:
  home: http://docs.enthought.com/apptools/
  license: BSD-3-Clause
  summary: application tools
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - grlee77
