{% set name = "apptools" %}
{% set version = "5.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apptools-{{ version }}.tar.gz
  sha256: 30580bf62a0d5dd616edd5e2b9958227633f35cb557c6860452a56809e6bd567

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - traits >=6.2.0
    - pyface
    - traitsui
    - configobj

test:
  imports:
    - apptools
    - apptools.logger.api
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://docs.enthought.com/apptools
  summary: application tools
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - grlee77
    - JaRoSchm
