{% set version = "5.2.1" %}

package:
  name: apptools
  version: {{ version }}

source:
  fn: apptools-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/a/apptools/apptools-{{ version }}.tar.gz
  sha256: c6268f5dfcf3088bcaf76a0003e50b7774d01b5258d7199b410b4852ff2246e3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - traits
    - pyface
    - traitsui
    - configobj
  run:
    - python
    - traits
    - pyface
    - traitsui
    - configobj

test:
  imports:
    - apptools
    - apptools.logger.api

about:
  home: http://docs.enthought.com/apptools/
  license: BSD-3-Clause
  summary: application tools
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - grlee77
