travis:
  secure:
    BINSTAR_TOKEN: 4RVS4p4cSAYpKDiBPAn/7NLr04T5/KT8K9HO1eI1eFaQWm4EsTBrbs7aMbSLAiz+bf3e/tIXbCq02F0Js8GQ2ZR66OtA6eB0kIa+qn2CLuDTJL8PfHFDro4lZPdj3iqg/hH4of5ZYZtH2/TqI6noCsDged+QVaZc1hwZStqnAFnEjJYCpVGN2iAusUkMhsE2mSC6SBZykXKOlmh0eaHnkyFcgpm+RhV5MaBlxZUGS5iqSho8pQRTB9Nv+fJelNYTC1bCdq8DgFl+T+LYNVG+Ly2pLu7U+YpKE1jss+5QCI49Df4g7OqR77ND0jbGHeHqGIyztCDBw8A5nyf+XXlncvduYy1NJ2zHt5DQOgimigGC9r53q7GUfIblFPvzBdx3zjzlbF4vdNJVPMFdtjMQZePWwY0u5oYWoIxj/yypKx5GEpuyBxgzDs2OX0Kp6SCewypzSY0zze8nweO343YM4XDeydYh6zLIyB7vZIBrw6YsDvhu1YSpNnhfd4gpmvDRRtyphlStXxq5UBTUJ0TsbPrLLDCmleZF9g7XstkNTkNl1MtqYAHiGiAfZKnbRk/T71qsJimGZsAcyEUrEocvxvlu9Pp+Yuj3sLEZYOSgCOv2i9X1nH6szGlZxnO/7JndPojqRHriQA0t6N1UsOop7HdkZ+hh3LBhSbyb3vss3Bs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
